-- =============================================================================
-- Skrip DDL (Data Definition Language) untuk Mandor Tracking System (MTS)
-- Target Database: Oracle
-- Dibuat berdasarkan ERD Final
-- =============================================================================

-- Menghapus tabel lama jika ada untuk eksekusi ulang yang bersih
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE location_visits CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE daily_summaries CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE work_plans CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE sync_logs CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE mst_params CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE permission_role CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE role_user CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE permissions CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE roles CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE employees CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- =============================================================================
-- Tabel Inti & RBAC
-- =============================================================================

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255 CHAR) NOT NULL,
    email VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    email_verified_at TIMESTAMP NULL,
    password VARCHAR2(255 CHAR) NOT NULL,
    remember_token VARCHAR2(100 CHAR) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    slug VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE permissions (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255 CHAR) NOT NULL,
    slug VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    group_name VARCHAR2(255 CHAR) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

-- =============================================================================
-- Tabel Master Data
-- =============================================================================

CREATE TABLE employees (
    id VARCHAR2(255 CHAR) PRIMARY KEY,
    user_id NUMBER NULL UNIQUE,
    name VARCHAR2(255 CHAR) NOT NULL,
    "position" VARCHAR2(255 CHAR) NOT NULL,
    plantation_group VARCHAR2(255 CHAR) NULL,
    wilayah VARCHAR2(255 CHAR) NULL,
    phone VARCHAR2(255 CHAR) NOT NULL,
    photo_url VARCHAR2(255 CHAR) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_employees_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE geofences (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    dwh_id NUMBER NOT NULL UNIQUE,
    name VARCHAR2(255 CHAR) NOT NULL,
    pg_group VARCHAR2(255 CHAR) NULL,
    region VARCHAR2(255 CHAR) NOT NULL,
    location_code VARCHAR2(255 CHAR) NOT NULL,
    area_size VARCHAR2(255 CHAR) NULL,
    coordinates CLOB, -- Oracle tidak punya tipe JSONB asli, CLOB adalah pilihan umum
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

-- =============================================================================
-- Tabel Operasional
-- =============================================================================

CREATE TABLE work_plans (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "date" DATE NOT NULL,
    employee_id VARCHAR2(255 CHAR) NOT NULL,
    geofence_id NUMBER NOT NULL,
    spk_number VARCHAR2(255 CHAR) NULL,
    activity_description CLOB NOT NULL,
    status VARCHAR2(255 CHAR) DEFAULT 'Draft' NOT NULL,
    created_by NUMBER NOT NULL,
    approved_by NUMBER NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_work_plans_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_plans_geofence_id FOREIGN KEY (geofence_id) REFERENCES geofences(id) ON DELETE CASCADE,
    CONSTRAINT fk_work_plans_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_work_plans_approved_by FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE daily_summaries (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "date" DATE NOT NULL,
    employee_id VARCHAR2(255 CHAR) NOT NULL,
    total_work_minutes NUMBER DEFAULT 0 NOT NULL,
    total_outside_area_minutes NUMBER DEFAULT 0 NOT NULL,
    total_distance_km NUMBER DEFAULT 0 NOT NULL,
    last_update TIMESTAMP NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_daily_summaries_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE location_visits (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "date" DATE NOT NULL,
    employee_id VARCHAR2(255 CHAR) NOT NULL,
    geofence_id NUMBER NOT NULL,
    entry_time TIMESTAMP NOT NULL,
    exit_time TIMESTAMP NOT NULL,
    visit_duration_minutes NUMBER NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_location_visits_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_location_visits_geofence_id FOREIGN KEY (geofence_id) REFERENCES geofences(id) ON DELETE CASCADE
);

-- =============================================================================
-- Tabel Konfigurasi & Log
-- =============================================================================

CREATE TABLE mst_params (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    param_key VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    param_value CLOB NOT NULL,
    description CLOB NULL,
    group_name VARCHAR2(255 CHAR) NULL,
    status NUMBER(1) DEFAULT 1 NOT NULL, -- 1 for TRUE, 0 for FALSE
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

CREATE TABLE sync_logs (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sync_type VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    last_sync_at TIMESTAMP NULL,
    status VARCHAR2(255 CHAR) NOT NULL,
    notes CLOB NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL
);

-- =============================================================================
-- Tabel Penghubung (Pivot Tables) untuk RBAC
-- =============================================================================

CREATE TABLE role_user (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_role_user_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_user_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE permission_role (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    permission_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT fk_permission_role_perm_id FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT fk_permission_role_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- =============================================================================
-- Tabel Data Tracking dari Firestore
-- =============================================================================

CREATE TABLE tracking_summaries (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR2(255 CHAR) NOT NULL,
    work_date DATE NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    total_duration_minutes NUMBER DEFAULT 0,
    total_distance_km NUMBER(10, 2) DEFAULT 0, -- Presisi untuk KM
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_tr_summaries_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT uq_summary_employee_date UNIQUE (employee_id, work_date)
);

CREATE TABLE tracking_points (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    summary_id NUMBER NOT NULL,
    latitude NUMBER(10, 7) NOT NULL,
    longitude NUMBER(11, 7) NOT NULL,
    battery_status NUMBER(3) NULL,
    recorded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_tr_points_summary_id FOREIGN KEY (summary_id) REFERENCES tracking_summaries(id) ON DELETE CASCADE
);
